### ISSUE TITLE
[Question] How to use droneoss without agent?

### ISSUE THREAD

**Issue by marktan93** [gary-kim/drone-oss#24]
I tried to bring up your docker image and everything seems good but for the pipeline stage, it only triggers the clone. 
I believe this is because of the agent you mentioned. 
Since there is no more agent how do you make things work?
Would you mind sharing? Thank you.

**Comment by gary-kim** [comment]
You can set it up to use a local docker agent by providing access to the docker socket using volumes. So adding: `-v "/var/run/docker.sock:/var/run/docker.sock"`. This way, jobs will be run on the local docker daemon as sibling containers.

Also make sure that `DRONE_AGENTS_DISABLED=true` is set. It should be automatically added by https://github.com/gary-kim/drone-oss/blob/master/Dockerfile.server.linux.amd64.patch but do double check.

**Comment by marktan93** [comment]
Thank you, Gary. I managed to build the working image now. 
It saves me a lot of time, thank you very much for the great works.
